name: Update Profile Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate README stats
        uses: teoxoy/profile-readme-stats@v3
        with:
          token: ${{ secrets.USER_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "update stats"
          git push
